# Generated by Django 4.2.1 on 2023-05-22 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosApp', '0003_alter_usuario_correo'),
        ('SuscripcionesApp', '0002_subscription_activate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'service')},
        ),
    ]
