# Generated by Django 4.2.1 on 2023-05-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuscripcionesApp', '0003_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
