# Generated by Django 4.2.1 on 2023-05-22 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosApp', '0003_alter_usuario_correo'),
        ('SuscripcionesApp', '0004_alter_subscription_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsuariosApp.usuario', to_field='correo'),
        ),
    ]
