# Generated by Django 4.2.1 on 2023-05-22 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuscripcionesApp', '0005_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuscripcionesApp.service', to_field='name'),
        ),
    ]
