# Generated by Django 4.2.1 on 2023-05-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuscripcionesApp', '0006_alter_service_name_alter_subscription_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='api_key',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='url_api',
            field=models.CharField(default='www', max_length=255),
        ),
    ]
